version: '3'

services:
  facefusion-cuda: 
    build:
      context: .
      dockerfile: Dockerfile.cuda
      network: host
    runtime: nvidia
    command: sleep infinity
    volumes:
    - ./:/app
    - ~/data/facefusion/:/app/.assets
    ports:
      - 7880:7860
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu, video ]
